name: "Build"

on:
  push:
    branches:
      - 'main'
      - 'releases/**'

permissions:
  # To create a new release
  contents: write

jobs:
  huawei:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v9
    # - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: "Pin the nixpkgs channel to nixos-unstable"
      # Works for the local user only! And this only pins the registry, which is
      # only used by flakes, it just happens that the DeterminateSystems nix
      # installer also sets extra-nix-path = nixpkgs=flake:nixpkgs, which makes
      # nix-build pick up on this, too.
      run: |
        nix registry add nixpkgs github:NixOS/nixpkgs/nixos-unstable
    - name: Build DO image
      run: |
        nix build .#nixosConfigurations.bootstrap.config.system.build.diskoImagesScript
        ./result --build-memory 4096
    - uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: {{ secrets.USER }}
        key: ${{ secrets.SSHKEY }}
        source: "main.raw"
        target: "/nixos.raw"
    # - uses: "actions/upload-artifact@v4"
    #   name: "Upload image artifact"
    #   with:
    #     name: "nixos-hwcloud-x86_64-linux.raw"
    #     path: "nixos.raw"
    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: latest
    #     prerelease: false
    #     files: |
    #       nixos-hwcloud-x86_64-linux.raw.zip
